# Generated by Django 4.1.3 on 2022-11-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='dish_category',
            field=models.ManyToManyField(to='menu.category'),
        ),
        migrations.AddField(
            model_name='menu',
            name='dish_cuisine',
            field=models.ManyToManyField(to='menu.cuisine'),
        ),
    ]
