# Generated by Django 4.1.3 on 2022-11-09 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_cuisine_menu_dish_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='dish_category',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='dish_cuisine',
        ),
        migrations.AddField(
            model_name='menu',
            name='dish_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='dish_cuisine',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='menu.cuisine'),
            preserve_default=False,
        ),
    ]
